version: '3.3'
services:
  backend:
    build:
      context: ../me-backend
      dockerfile: ./Dockerfile
    image: me-back
    ports:
      - "7000:8080"
    container_name: "back_container"
    depends_on:
      - db
  db:
    image: aashreys/mongo-auth:latest
    container_name: "db_container"
    ports:
      - "27017:27017"
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin123
      - MONGODB_APPLICATION_DATABASE=mars
      - MONGODB_APPLICATION_USER=app
      - MONGODB_APPLICATION_PASS=password
    volumes:
      - mongodata:/data/db
  frontend:
          image: webdevops/apache:latest
          container_name: "front_container"
          volumes:
            - ../me-frontend:/app
          ports:
            - 80:80
            - 443:443
          links:
            - backend
volumes:
  mongodata:


